#### <font color="royalblue">SPRINT 10: Analítica de datos en Pandas</font>
En esta tarea te enfrentarás a un ejercicio de limpieza y analítica de datos.  
Tenemos un dataset proveniente de una encuesta a nuestros trabajadores y trabajadores, y debemos garantizar que los datos se procesan correctamente, tanto en formato como en legibilidad.

#### <font color="royalblue">Nivel 1</font>

1. Importa como un DataFrame el archivo sprint10.xlsx. Asegúrate de que el archivo se importa correctamente, con los nombres de columnas que le corresponden, sin manipular el archivo original.  
Ordena el DataFrame por el país de origen. En caso de empate, ordena por el nombre de la ciudad.  
Muestra las primeras 10 filas.  
Adicionalmente, realiza un *print* donde compruebe que el DNI sólo tiene valores únicos.

<font color="royalblue">Objetivo:</font>  

- Importar la libreria **pandas** y llamarla com el alias **pd**,
- Cargar el archivo excel *sprint10.xlsx* a través de **pd.read_excel**, guardado en variable *dataset*,
- Usar parámetros del método de carga **pd.read_excel** para importar correctamente:
    - Para indicar fila con nombre de columnas **header=2**, 
    - Para saltar linea al inicio **skiprows=[2]**, 
    - Para elegir columna como indice **index_col=0**,  
- Crear dataframe en variable *df* a partir de **pd.DataFrame()**,
- Ordenar dataframe con el método **.sort_values**, en parametro **by=** indicar la columna por la cual se quiere ordenar, en este ejercicio primero por país de origen y después por ciudad. Se almacena en dataframe *df_pais*,
- Desplagar en pantalla solo las primeras 10 filas con el método **.head(10)** indicando en paréntesis número de filas que se quieren ver.

In [6]:
import pandas as pd

dataset = pd.read_excel("sprint10.xlsx", header=2, skiprows=[2], index_col=0)

df = pd.DataFrame(dataset)

df_pais = df.sort_values(by=["País d'origen","Ciutat"]).head(10)

print(df_pais.head(10))

print("En los datos existen DNI duplicados?:",df["DNI"].duplicated().any())

       Nom              Cognoms        DNI País d'origen   Ciutat  \
21     Mia    Schneider Fischer  28973553Z      Alemanya   Berlín
154  Laura    Schneider Fischer  37399141L      Alemanya   Berlín
224    Lea  Schneider Schneider  37368317L      Alemanya   Berlín
278    Mia              Fischer  21390098Z      Alemanya   Berlín
602  Jonas            Schneider  44060014R      Alemanya   Berlín
871    Lea              Fischer  14773153R      Alemanya   Berlín
281    Lea               Müller  23266650S      Alemanya  Hamburg
435   Anna               Müller  83274277X      Alemanya  Hamburg
444  Laura       Schmidt Müller  60161784X      Alemanya  Hamburg
487  Lukas       Müller Fischer  60982309S      Alemanya  Hamburg

     Dia de Naixement  Mes de Naixement  Any de Naixement Gènere  \
21                 22                10              1976      A
154                 2                 2              1958      D
224                23                10              2005      D
278                11                 8              1950      D
602                22                11              1985      H
871                 9                 9              1986      D
281                14                 4              2003      D
435                 1                 1              1987      D
444                15                 6              1987     NC
487                28                 3              1971      H

    Salari mensual  Fills  No Fills Grup Professional
21           951 €    NaN       1.0            Grup A
154        1.769 €    1.0       NaN            Grup B
224        2.013 €    NaN       1.0            Grup B
278        1.557 €    1.0       NaN            Grup B
602        2.754 €    1.0       NaN            Grup D
871        1.370 €    1.0       NaN            Grup A
281        1.314 €    NaN       1.0            Grup A
435        2.464 €    NaN       1.0            Grup C
444        2.035 €    1.0       NaN            Grup C
487        2.042 €    NaN       1.0            Grup B
En los datos existen DNI duplicados?: False

2. Crea una columna que sea el nombre completo.  
Crea una columna si la persona ha nacido en España o no.  
Pone el DNI como índice del DataFrame (nombres de filas).  
Sustituye el nombre de las columnas Día de Nacimiento, Mes de Nacimiento y Año de Nacimiento por Día, Mes y Año.  
Sustituye a H por Hombre, D por Mujer, A por Otros y NC por un dato faltante (enano/null/na).  
Muestra todos los cambios que has realizado en una sola tabla.

<font color="royalblue">Objetivo:</font>  

- Crear columna *"Nom complet"* a partir de columnas *"Nom"* y *"Cognoms"*, con operador suma (+) y estableciendo en espacio(" "),
- Crear la función **nacidos_españa()** con **def** para definir si una persona ha nacido en España, usando como parámetro *país_origen* "Espanya" en un condicional **if-else**, retornado *False* o *True*,
- Crear columna *"Españoles"* para aquellos nacidos en España, a través del método **.apply()** e introduciendo como parámetro la función **nacidos_españa** sobre la columna *"País d'origen"*,
- Establecer la columna *"DNI"* como indice del dataframe *df*, a partir del método **.set_index()**, en parámetros se indica la columna que será el index y **inplace=True** para guardar cambio en dataframe original *df*,
- Renombrar columnas con el método **.rename()**, definiendo en parámetros **columns=** las columnas a modificar por medio de un diccionario donde se indica nombre viejo y nombre nuevo:
    - 'Dia de Naixement': 'Dia',
    - 'Mes de Naixement': 'Mes', 
    - 'Any de Naixement': 'Any'
- Renombrar valores en columna *"Gènere"* usando el método **.replace()**, como parámetro se indica nombre viejo y nombre nuevo en formato de diccionario:
    - "H": "Home", 
    - "D": "Dona", 
    - "A": "Altres", 
    - "NC": "null"
- Aplicar en cambio de renombrar tanto en columnas de fechas como en datos de género el parámetro **inplace=True**, para mantener las modificaciones realizadas con ambos métodos **.rename()** y **.replace()** en el dataframe original *df*,
- Crear *tabla_mod* donde se guarda solo las columnas donde se han modificado datos del dataframe *df*.

In [7]:
df["Nom complet"] = df["Nom"] + " " + df["Cognoms"]

def nacidos_españa(pais_origen):
    if pais_origen == "Espanya":
        return True
    else:
        return False

df["Nascut Espanya"] = df["País d'origen"].apply(nacidos_españa)

df.set_index("DNI", inplace=True)

df.rename(columns={"Dia de Naixement": "Dia", "Mes de Naixement": "Mes", "Any de Naixement": "Any"}, inplace=True)

df["Gènere"] = df["Gènere"].replace({"H": "Home", "D": "Dona", "A": "Altres", "NC": "null"})

tabla_mod = df[["Nom complet","Nascut Espanya", "Dia", "Mes", "Any", "Gènere"]]
tabla_mod

                       Nom complet  Nascut Espanya  Dia  Mes   Any  Gènere
DNI
16928694K      Inês Ferreira Silva           False   25    2  1953    Dona
27724652S   Clara Sánchez Martínez            True   18    3  1996    Dona
38141675A             Fatima Fassi           False    6   11  2005  Altres
59157262R  Khadija Bennani Bennani           False   20    1  1995    Dona
69630528M      Toni Sánchez García            True    9    8  1999    Home
...                            ...             ...  ...  ...   ...     ...
25161375F      Marta Ferrer Ferrer            True    1    6  1951    Dona
52145541P              Joan García            True   11    4  1959    Home
69760120X     Laia Ferrer Martínez            True   11   11  1980    Dona
82947791W             Jordi García            True   23    5  1984    Home
89253307W      Clara Sánchez López            True    1    8  1952    Dona

[1000 rows x 6 columns]

3. Junta las columnas Fills y No Fills en una sola columna, utilizando el método .apply() y definiendo una función que resuelva el problema. La columna nueva debe llamarse "Fills" y tomar los valores "Sí" o "No".

<font color="royalblue">Objetivo:</font>  

- Juntar la información de las columnas *"Fills"* y *"No Fills"* en una solo columna. Para esto se cambia la columna "Fills" a partir de los datos de la columna "No Fills" y luego se elimina la columna "No Fills":
    - Crear la función **hijos()** con **def** para definir si una persona tiene hijos o no, usando como parámetro *hijo* en un condicional **if-else**, retornado *"No"* o *"Si"*,
    - Modificar columna *"Fills"*, a través del método **.apply()** e introduciendo como parámetro la función **hijos** sobre la columna *"No Fills"*, quedando como valores *"Si"* y *"No"*
    - Eliminar la columna *"No Fills"* con el método **.drop()**, se pasa como parámetro **columns=** la columna a borrar, junto con **inplace=True** para mantener cambio en el dataframe original *df*.

In [8]:
def hijos(hijo):
    if hijo == 1.0: 
        return "No"
    else:
        return "Si"

df["Fills"] = df["No Fills"].apply(hijos)
df.drop(columns=["No Fills"], inplace=True)
df

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,Grup Professional,Nom complet,Nascut Espanya
DNI,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Dona,1.144 €,No,Grup B,Inês Ferreira Silva,False
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Dona,1.253 €,Si,Grup A,Clara Sánchez Martínez,True
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,Altres,1.441 €,Si,Grup A,Fatima Fassi,False
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Dona,1.944 €,No,Grup B,Khadija Bennani Bennani,False
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Home,1.043 €,No,Grup A,Toni Sánchez García,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Dona,1.216 €,No,Grup B,Marta Ferrer Ferrer,True
52145541P,Joan,García,Espanya,Sevilla,11,4,1959,Home,971 €,No,Grup A,Joan García,True
69760120X,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Dona,682 €,No,Grup A,Laia Ferrer Martínez,True
82947791W,Jordi,García,Espanya,Barcelona,23,5,1984,Home,1.699 €,Si,Grup C,Jordi García,True
89253307W,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Dona,1.217 €,No,Grup A,Clara Sánchez López,True

4. Crea una tabla resumen que permita ver el sueldo medio, mediano, mínimo y máximo por Género.  
Ordena la tabla en función del sueldo medio.

<font color="royalblue">Objetivo:</font>  

- Modificar la columna *"Salari mensual"* para poder aplicar funciones aritmeticas.
    - Retirar el símbolo "€" con el método **.replace()**,
    - Retirar el punto "." como separador de mil con el método **.replace()**,
    - Definir tipo de formato como *int* con el método **.astype()**
- Agrupar por la columna *"Gènere"* usando el método **.groupby()**
- Calcular las funciones pedidas a partir del método **.agg()**, como parámetro se pasa en fomato de diccionario:
    - clave: columna sobre la que se aplicaran las funciones *"Salari mensual"* y 
    - valor: las fuciones a determinar ***["mean", "median", "min", "max"]** 
- Ordenar el dataframe *"df"* con el método **.sort_values()** basados en el salario medio.

In [9]:
df["Salari mensual"] = df["Salari mensual"].str.replace(" €", "").str.replace(".", "").astype(int)

df.groupby("Gènere").agg({"Salari mensual": ["mean", "median", "min", "max"]}).sort_values(by=("Salari mensual", "mean"))

       Salari mensual
                 mean  median  min   max
Gènere
Dona      1469.443182  1361.5  665  3021
null      1568.866667  1443.0  758  2969
Altres    1626.588235  1545.0  703  3175
Home      1643.249443  1531.0  737  3356

5. Crea una tabla resumen con el salario medio por género (filas) y país de origen (columnas).  
Añade las medias a los márgenes de la tabla.  
(EXTRA): Aplica formato condicional en la tabla para ver en un color más intenso los valores más elevados

<font color="royalblue">Objetivo:</font>  

- Crear la variable *tabla_resumen* con la función **pd.crosstab()** donde los parámetros son:
    - **index=**, valores de *"Génere"* como filas,
    - **columns=** valores de *"País d'origen"* como columnas,
    - **values=** valores de *"Salari mensual"* como datos para llenar el dataframe *"df"*,
    - **aggfunc=** función u operación matemática que será aplicada a los datos (values), este caso **"mean"**,
    - **margins=True** ,
- Dar formato en el display a los valores máximos de cada columna de la tabla con **.style**. Para esto se define a traves **.apply()** una función **lambda** que establece con un condicional **if-else** y un bucle **for** el fondo azul para los valores máximos *"v == x.max()"* de cada columna *x*.

In [10]:
tabla_resumen =pd.crosstab(index=df["Gènere"], columns=df["País d'origen"], values=df["Salari mensual"], aggfunc="mean", margins=True)

tabla_resumen.style.apply(lambda x:["background: royalblue" if v == x.max() else "" for v in x])


6. Crea una nueva columna que sea la fecha de nacimiento en formato Datetime a partir de las columnas día, mes y año. Utilizando esta columna crea una función que dada una fecha, te calcule la edad actual a día de hoy.  
Utiliza la función que acabas de crear para generar una columna nueva en DataFrame con la edad actual.

<font color="royalblue">Objetivo:</font>  

- Importar módulo **datetime** para manejar fechas y horas,
- Crear la columna *"Data naixement"* a partir de las columnas *"Dia"*, *"Mes"* y *"Any"*, para ello armo el formato:
    - Ordenando por dia, mes y año,
    - Separando con simbolo "/" cada valor,
    - Uniendo con operador "+",
    - Modificando formato de cada columna con el método **.astype()**, de numerico a texto con parámetro *"str"*.
- Dar formato de fecha a la columna *"Data naixement"* recien creada con la función **pd.to_datetime()**. Los parámetros a usar son dato a modifica (fecha de nacimiento), **format=** tipo de formato de entrada (dia-mes-año) y **errors="coerce"** para manejar valores inválidos,
- Crear la función **edad_actual()** para calcular la edad de cada persona a la fecha actual:
    - Usa como parámetro la *"fecha_nacimiento"*,
    - Determina como variable *hoy* la fecha actual con **datetime.now()**
    - Calcula la variable *edad* restando la variable *hoy* a la fecha de nacimiento,
    - Con **.dt.days** transfoma la resta en días y luego divide entre 365 días para definir los años de edad.
- Crear columna *"Edat"* a través de la función recine creada **edad_actual()** e introduciendo como parámetro la columna *"Data naixement"*,

In [11]:
from datetime import datetime
df["Data naixement"] = df["Dia"].astype(str) + "/" + df["Mes"].astype(str) + "/" + df["Any"].astype(str)
df["Data naixement"] = pd.to_datetime(df["Data naixement"], format="%d/%m/%Y", errors="coerce")

def edad_actual(fecha_nacimiento):
    hoy = datetime.now()
    edad = (hoy - fecha_nacimiento).dt.days // 365
    return edad
df["Edat"] = edad_actual(df["Data naixement"])
df

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,Grup Professional,Nom complet,Nascut Espanya,Data naixement,Edat
DNI,,,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Dona,1144,No,Grup B,Inês Ferreira Silva,False,1953-02-25,72
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Dona,1253,Si,Grup A,Clara Sánchez Martínez,True,1996-03-18,29
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,Altres,1441,Si,Grup A,Fatima Fassi,False,2005-11-06,20
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Dona,1944,No,Grup B,Khadija Bennani Bennani,False,1995-01-20,31
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Home,1043,No,Grup A,Toni Sánchez García,True,1999-08-09,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Dona,1216,No,Grup B,Marta Ferrer Ferrer,True,1951-06-01,74
52145541P,Joan,García,Espanya,Sevilla,11,4,1959,Home,971,No,Grup A,Joan García,True,1959-04-11,66
69760120X,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Dona,682,No,Grup A,Laia Ferrer Martínez,True,1980-11-11,45
82947791W,Jordi,García,Espanya,Barcelona,23,5,1984,Home,1699,Si,Grup C,Jordi García,True,1984-05-23,41
89253307W,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Dona,1217,No,Grup A,Clara Sánchez López,True,1952-08-01,73

#### <font color="royalblue">Nivel 2</font>

1. Utilizando el siguiente DataFrame, adjunta la columna "Increment" al dataframe del nivel anterior.  
Actualiza la columna salario en función de los porcentajes que se adjuntan. No modifiques manualmente los incrementos, escribe código Python para realizar las conversiones necesarias.  
`df_increment = pd.DataFrame({"Grup":["Grup A","Grup B","Grup C", "Grup D" ] , "Increment":`
`["5%","3,5%","2%","8%"]})`

![Ejemplo dicc invertido](imatgeS10-1.jpg)

<font color="royalblue">Objetivo:</font>  

- Cargar los datos del enunciado de incremento y grupo como dataframe con la función **pd.DataFrame()**, en la variable *"df_increment"*,
- Cambiar la columna indice del nuevo dataframe con el método **.set_index()**, basados en la columna *"Grup"*,
- Modificar formato de *"Increment"* para aplicar calculos a futuro, 
    - Eliminar el simbolo *"%"* con **.str.replace()**,
    - Reemplazar la coma *","* por punto *"."* como delimitador decimal con **.str.replace()**,
    - Cambiar formato a *"float"* con **.astype()** y dividirlo entre 100.
- Modificar la columna *"Increment"* desplegando en patalla como porcentaje con **.style.format()**,
- Adjuntar la columna *"Increment"* de dataframe *"df_increment"* al dataframe principal *"df"*. Usando la función **pd.merge()** se indican los parámetros, al inicio los dataframe que se unen y la columna común a ambos dataframe: 
    - En *"df"* la columna *"Grup Professional"*, integrado con el parámetro *"left_on="*,
    - En *"df_increment"* la columna *"Grup"* convertida en índice, integrado con el parámetro *"right_index=True"*.
- Crear la función **"aplicar_incremento()"** con **def** para actualizar los salarios a partir de los porcentajes de incremento:
    - Se establecen 2 parámetros *"salario"* y *"incremento"*,
    - Se define la variable *"nuevo_salario"* para guardar el cálculo.
- Calcular la nueva columna *Salari nuevo"* por medio de la función recien creada **"aplicar_incremento()"**, siendo los parámetros de entrada las columnas *"Salari mensual"* y *"Increment"*

In [ ]:
df_increment = pd.DataFrame({"Grup":["Grup A","Grup B","Grup C", "Grup D"] , "Increment":["5%","3,5%","2%","8%"]})
df_increment.set_index("Grup", inplace=True)
df_increment["Increment"] = df_increment["Increment"].str.replace("%","").str.replace(",",".").astype(float)/100
df_increment.style.format({"Increment":"{:.1f}%"})
df_increment

df= pd.merge(df, df_increment, left_on="Grup Professional", right_index=True)

def aplicar_incremento(salario, incremento):
    nuevo_salario = salario * (1 + incremento)
    return nuevo_salario    
df["Salari nuevo"] = aplicar_incremento(df["Salari mensual"], df["Increment"])
df

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,Grup Professional,Nom complet,Nascut Espanya,Data naixement,Edat,Increment,Salari nuevo
DNI,,,,,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Dona,1144,No,Grup B,Inês Ferreira Silva,False,1953-02-25,72,0.035,1184.04
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Dona,1253,Si,Grup A,Clara Sánchez Martínez,True,1996-03-18,29,0.050,1315.65
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,Altres,1441,Si,Grup A,Fatima Fassi,False,2005-11-06,20,0.050,1513.05
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Dona,1944,No,Grup B,Khadija Bennani Bennani,False,1995-01-20,31,0.035,2012.04
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Home,1043,No,Grup A,Toni Sánchez García,True,1999-08-09,26,0.050,1095.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Dona,1216,No,Grup B,Marta Ferrer Ferrer,True,1951-06-01,74,0.035,1258.56
52145541P,Joan,García,Espanya,Sevilla,11,4,1959,Home,971,No,Grup A,Joan García,True,1959-04-11,66,0.050,1019.55
69760120X,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Dona,682,No,Grup A,Laia Ferrer Martínez,True,1980-11-11,45,0.050,716.10
82947791W,Jordi,García,Espanya,Barcelona,23,5,1984,Home,1699,Si,Grup C,Jordi García,True,1984-05-23,41,0.020,1732.98
89253307W,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Dona,1217,No,Grup A,Clara Sánchez López,True,1952-08-01,73,0.050,1277.85

2. Utilizando un bucle, exporta en 4 archivos (formato .xlsx o .csv) los datos de cada Grupo Profesional.  
Por ejemplo: "datos_GrupA.xlsx" , "datos_GrupB.xlsx" ...  
Exporta un 5º DataFrame en formato .xlsx o .csv que contenga cuántos trabajadores hay por cada Grupo Profesional, cuál es su sueldo medio y cuál es su edad media.

<font color="royalblue">Objetivo:</font>  

- Crear un bucle con **for** donde los 4 grupos establecen el parámetro iterador *grup* sobre la columna *"Grup Professional"*:
    - Definir la variable *df_grup* para cada almacenar los datos de cada grupo, determinado durante cada iteración de *grup*,
    - Exportar con **.to_csv()** los datos *df_grup* en el archivo *"datos_grup.csv"*, adicionalmente se elimina el espacio para cada grupo con **.replace()** para evitar espacios en el nombre del archivo. 
    - Uso del parámetro **encoding="utf-8"** para exportar de forma correcta acentos y carácteres especiales.
- Generar finalmente los archivos *"datos_GrupA.csv"*, *"datos_GrupB.csv"*, *"datos_GrupC.csv"* y *"datos_GrupD.csv"*,
- Crear un dataframe con datos de cada grupo profesional de nombre *df_Grups* con **.groupby()**, estableciendo como columna base para agrupar *"Grup Professional"* y con el método **.agg()** usando como parámetro en formato diccionario los datos a exportar:
    - "Nom":"count" número de trabajadores,
    - "Salari mensual": "mean" salario medio,
    - "Edat": "mean" edad media.
- Exportar *"df_Grups"* con el método **.to_csv()** en el archivo de nombre *"grups_professionals.csv"*.

In [13]:
for grup in df["Grup Professional"]:
    df_grup = df[df["Grup Professional"] == grup]
    df_grup.to_csv(f"datos_{grup.replace(' ', '')}.csv", encoding="utf-8")

df_Grups=df.groupby("Grup Professional").agg({"Nom":"count", "Salari mensual": "mean", "Edat": "mean"})
df_Grups.to_csv("grups_professionals.csv")
df_Grups

                   Nom  Salari mensual       Edat
Grup Professional
Grup A             490     1155.546939  49.038776
Grup B             318     1666.232704  47.767296
Grup C             137     2244.306569  50.905109
Grup D              55     2871.127273  44.890909